# Generated by Django 2.0.1 on 2018-02-28 08:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(choices=[('Videos', 'video'), ('Pictures', 'picture'), ('Gifs', 'gif')], default='Videos', max_length=10)),
                ('cat_file', models.FileField(blank=None, default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('post_desc', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('post_file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('post_disp_img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default=None, max_length=100)),
                ('topic_type', models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Funny', 'Funny')], default='Health', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_country', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user_city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user_sec_ques', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('user_sec_ans', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('user_dob_month', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('user_dob_date', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('user_dob_year', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('user_pic', models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to='')),
                ('user_pic_crop', image_cropping.fields.ImageRatioField('user_pic', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='user pic crop')),
                ('user_web_url', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('user_abtme_title', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user_abtme_desc', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='post_info',
            name='post_user',
            field=models.ForeignKey(default=None, on_delete=None, to='myapp.User_info'),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_top',
            field=models.ForeignKey(default=None, on_delete=None, to='myapp.Topic'),
        ),
    ]
