# Generated by Django 2.0.1 on 2018-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_info',
            name='post_publish_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
