# Generated by Django 2.0.1 on 2018-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='dob_date',
            new_name='user_dob_date',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='dob_month',
            new_name='user_dob_month',
        ),
        migrations.RenameField(
            model_name='user_info',
            old_name='dob_year',
            new_name='user_dob_year',
        ),
    ]
