# Generated by Django 2.0.1 on 2018-02-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180213_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_pic',
            field=models.FileField(blank=True, default=None, null=True, upload_to='myapp/images/'),
        ),
    ]
