# Generated by Django 2.0.1 on 2018-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180228_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_info',
            name='post_publish_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
