# Generated by Django 2.0.1 on 2018-02-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180213_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
