# Generated by Django 2.0.1 on 2018-03-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_info_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='post_desc',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post_info',
            name='post_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
