# Generated by Django 2.0.1 on 2018-03-02 01:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('myapp', '0005_auto_20180301_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_info',
            name='post_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
