# Generated by Django 2.0.1 on 2018-02-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180213_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_city',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
