# Generated by Django 2.0.1 on 2018-02-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_info_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_web_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
