# Generated by Django 2.0.1 on 2018-03-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_post_info_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_info',
            old_name='post_tags',
            new_name='tags',
        ),
    ]
