# Generated by Django 2.0.1 on 2018-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180302_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
                ('rel_from_user', models.ForeignKey(on_delete=None, related_name='from_user', to='myapp.User_info')),
                ('rel_to_user', models.ForeignKey(on_delete=None, related_name='to_user', to='myapp.User_info')),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_relationship',
            field=models.ManyToManyField(related_name='related_to', through='myapp.Relationship', to='myapp.User_info'),
        ),
    ]
