# Generated by Django 2.0.1 on 2018-03-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180303_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='post_disp_img',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to=''),
        ),
    ]
