# Generated by Django 2.0.1 on 2018-02-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180215_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_dob_date',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_dob_month',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_dob_year',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_sec_ans',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_sec_ques',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
