# Generated by Django 2.0.1 on 2018-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180303_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='post_desc',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
