# Generated by Django 2.0.1 on 2018-03-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180306_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_desc', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('comm_publish_date', models.DateField(blank=True, default=None, null=True)),
                ('comm_post', models.ForeignKey(default=None, on_delete=None, to='myapp.Post_info')),
                ('comm_user', models.ForeignKey(default=None, on_delete=None, to='myapp.User_info')),
            ],
        ),
    ]
