# Generated by Django 2.0.1 on 2018-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180215_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_pic',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to=''),
        ),
    ]
