# Generated by Django 2.0.1 on 2018-02-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180215_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_abtme_desc',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='user_abtme_title',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
