# Generated by Django 2.0.1 on 2018-03-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comm_publish_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
