# Generated by Django 2.0.1 on 2018-02-18 01:49

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20180215_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_pic_crop',
            field=image_cropping.fields.ImageRatioField('user_pic', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='user pic crop'),
        ),
    ]
