# Generated by Django 2.0.1 on 2018-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_comments_comm_publish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_post', models.ForeignKey(default=None, on_delete=None, to='myapp.Post_info')),
                ('like_user', models.ForeignKey(default=None, on_delete=None, to='myapp.User_info')),
            ],
        ),
    ]
