# Generated by Django 2.0.1 on 2018-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='rel_status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked'), (3, 'Following Self')]),
        ),
    ]
