# Generated by Django 2.0.1 on 2018-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180221_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='myapp.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_top',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=None, to='myapp.Topic'),
        ),
    ]
