# Generated by Django 2.0.1 on 2018-03-30 17:41

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0015_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GenericStringTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_genericstringtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myapp_genericstringtaggeditem_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post_info',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='myapp.GenericStringTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='fav_post',
            field=models.ForeignKey(default=None, on_delete=None, to='myapp.Post_info'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='fav_user',
            field=models.ForeignKey(default=None, on_delete=None, to='myapp.User_info'),
        ),
    ]
