# Generated by Django 2.0.1 on 2018-03-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180330_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_pic',
            field=models.ImageField(blank=True, default='default_user.jpg', null=True, upload_to=''),
        ),
    ]
