# Generated by Django 2.0.1 on 2018-02-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180227_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_top',
        ),
    ]
