# Generated by Django 2.0.1 on 2018-02-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20180227_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_info',
        ),
    ]
