# Generated by Django 2.0.1 on 2018-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20180227_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_info',
            name='post_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
